jobs:

- name: setArrayStorage
  job:
    set:
      val: "[1,2,3]"

- name: deployArrayConstructor
  job:
    deploy:
      contract: ./storage.sol
      instance: SimpleConstructorArray
      data: 
        - $setArrayStorage
        - [4, 5, 6]
      wait: true

- name: queryArrayStorage
  job:
    query-contract:
      destination: $deployArrayConstructor
      function: get

- name: assertArrayStorage
  job:
    assert:
      key: $queryArrayStorage
      relation: eq
      val: $setArrayStorage
